name: signature_pad
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  simple_logger: ^1.9.0+2
  riverpod_annotation: ^2.1.1
  go_router: ^10.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sign_button: ^2.0.4
  flutter_spinkit: ^5.2.0
  syncfusion_flutter_signaturepad: ^22.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  riverpod_generator: ^2.2.4
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
